include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    public_member_api_docs: ignore
    always_use_package_imports: ignore
    avoid_catches_without_on_clauses: ignore
    document_ignores: ignore

linter:
  rules:
    prefer_relative_imports: true
