name: j2m
description: "A new Flutter project."
publish_to: "none"
version: 0.0.14

environment:
  sdk: ^3.8.1

dependencies:
  change_case: ^2.2.0
  flutter:
    sdk: flutter
  flutter_code_editor: ^0.3.2
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_native_splash: ^2.4.5
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: "RobotoMono"
      fonts:
        - asset: assets/fonts/RobotoMono-VariableFont_wght.ttf
