name: j2m
description: "A new Flutter project."
publish_to: "none"
version: 0.0.4

environment:
  sdk: ^3.7.0

dependencies:
  change_case: ^2.2.0
  flutter:
    sdk: flutter
  flutter_code_editor: ^0.3.2
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: "RobotoMono"
      fonts:
        - asset: assets/fonts/RobotoMono-VariableFont_wght.ttf
